### PR TITLE
issue #5 fix unorderable types: str() >= int() with limit

### PR DESCRIPTION
**Pull request by shalakhin**

### CODE REVIEW

**Comment by shalakhin** [comment]
@and3rson so you can merge it?

**Comment by and3rson** [comment]
@shalakhin thanks for the fix! Sorry for delays, been having a lot of work recently...

**Comment by shalakhin** [comment]
@and3rson could you add me to contributors?

**Comment by shalakhin** [comment]
Thank you too. I will check if there are improvements (I actually have few in my mind)

**Pull request merged**
