### PR TITLE
Added fallback for django 1.11

### PR DESCRIPTION
**Pull request by sheeshmohsin**
There is error when I tried to implement searchable select in django 1.11, I fixed it using the code in this pull request. Please review the code and merge it.

### CODE REVIEW

**Comment by sheeshmohsin** [comment]
Hi, I am not able to detect what's failed? and also I am new to coveralls, so not sure what is decreased coverage? Can you please point me to the error or possible bugs in my code so that i can fix?

**Comment by and3rson** [comment]
@sheeshmohsin I will add info about testing coverage locally into readme in few minutes, stay tuned :)

**Comment by sheeshmohsin** [comment]
Cool, Thanks

**Comment by and3rson** [comment]
@shalakhin Please check out the updated readme, I've added info on how to run tests.
Your branch should now have both checks passing once you merge master in.

**Comment by and3rson** [comment]
@sheeshmohsin any luck? Simply merging master into your branch should do the trick :)

**Comment by sheeshmohsin** [comment]
@and3rson I will do by tonight (IST)  after office. Thanks for the informations :)

**Comment by and3rson** [comment]
I've merged it manually, waiting for the tests

**Comment by sheeshmohsin1** [comment]
Thanks for merging. Apologies for the delay from my side, was bit busy :)

**Comment by sheeshmohsin** [comment]
Thanks, Apologies for the delay from my side, was bit busy

**Pull request merged**
